services:
  api:
    build: .
    container_name: yamabiko-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

      # Gemini APIキーを外から注入する場合
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: yamabiko-postgres
    image: postgres:${DB_VERSION}
    platform: linux/x86_64
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      interval: 30s
      retries: 6
      start_period: 30s
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-h",
          "${DB_HOST}",
          "-d",
          "${DB_NAME}",
        ]
      timeout: 5s
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql:ro

volumes:
  db-data:
